name: Deploy to Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit Cloud
      run: streamlit deploy --app-path app/main.py --project-url https://github.com/khurshiduktamov/aqi-prediction-app
      env:
        STREAMLIT_API_TOKEN: ${{ secrets.STREAMLIT_API_TOKEN }}
